from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_voice_preview_and_allowed_numbers'
 down_revision = 'add_kb_providers_column'
 branch_labels = None
 depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('voice_preview_url', sa.String(), nullable=True))
    op.add_column('tenant', sa.Column('allowed_phone_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default=sa.text('jsonb_build_object()')))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'voice_preview_url')
    op.drop_column('tenant', 'allowed_phone_numbers')
    # ### end Alembic commands ###
